@baseUrl = http://localhost:8000/api/v1
@contentType = application/json

### 获取邮件验证码
POST http://localhost:8000/api/v1/auth/send-code
Content-Type: application/json
    
{
"email": "limq0755@163.com"
}

### 注册新用户
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json
    
{
    "email": "test_auto@example.com",
    "password": "test123456",
    "verification_code": "317511"
}

### 删除用户


### 登录
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/x-www-form-urlencoded

username=limq0755@163.com&password=qq123456

### 获取个人信息
@authToken = {{login.response.body.access_token}}
### 
GET {{baseUrl}}/users/me
Authorization: Bearer {{authToken}}

### 忘记密码
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
    "email": "limq0755@163.com"
}

### 重置密码
POST {{baseUrl}}/auth/reset-password

{
    "email": "limq0755@163.com",
    "new_password": "qq19880305",
    "verification_code": "636880"
}

### 创建文章
# @name create_post
POST {{baseUrl}}/posts/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "FastAPI 入门教程",
    "content": "FastAPI 是一个现代、快速的 Web 框架...",
    "tags": ["Python", "FastAPI", "Web开发"]
}


### 发布文章
@post_id = {{create_post.response.body.id}}
PATCH {{baseUrl}}/posts/{{post_id}}/publish
Authorization: Bearer {{authToken}}
Content-Type: application/json


### 获取已发布文章列表
GET {{baseUrl}}/posts/?page=1&size=20