"""add_session_id_to_post_view_and_enhance_indexes

Revision ID: 0c503c0a63ca
Revises: a14028f2192b
Create Date: 2025-10-27 11:32:27.061087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c503c0a63ca'
down_revision: Union[str, Sequence[str], None] = 'a14028f2192b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_views', sa.Column('session_id', sa.String(length=32), nullable=True, comment='会话标识符（用于会话级别防刷）'))
    op.create_index('idx_session_post_time', 'post_views', ['session_id', 'post_id', 'viewed_at'], unique=False)
    op.create_index('idx_session_viewed', 'post_views', ['session_id', 'viewed_at'], unique=False)
    op.create_index('idx_user_post_time', 'post_views', ['user_id', 'post_id', 'viewed_at'], unique=False)
    op.create_index(op.f('ix_post_views_session_id'), 'post_views', ['session_id'], unique=False)
    op.alter_column('posts', 'like_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='点赞次数统计',
               existing_nullable=False)
    op.alter_column('posts', 'favorite_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='收藏次数统计',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'favorite_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='收藏次数统计',
               existing_nullable=False)
    op.alter_column('posts', 'like_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='点赞次数统计',
               existing_nullable=False)
    op.drop_index(op.f('ix_post_views_session_id'), table_name='post_views')
    op.drop_index('idx_user_post_time', table_name='post_views')
    op.drop_index('idx_session_viewed', table_name='post_views')
    op.drop_index('idx_session_post_time', table_name='post_views')
    op.drop_column('post_views', 'session_id')
    # ### end Alembic commands ###
