"""add deleted_at field to users

Revision ID: 2e3ee01bbf0e
Revises: b9cf7908383e
Create Date: 2025-10-05 06:04:46.213854

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e3ee01bbf0e"
down_revision: str | Sequence[str] | None = "b9cf7908383e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="软删除时间（用户主动删除账号）",
        ),
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="账户是否激活（管理员可禁用）",
        existing_comment="账户是否激活（软删除标记）",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="账户是否激活（软删除标记）",
        existing_comment="账户是否激活（管理员可禁用）",
        existing_nullable=False,
    )
    op.drop_column("users", "deleted_at")
    # ### end Alembic commands ###
